CREATE TABLE `Teams`(
    yearID INTEGER,
    lgID CHAR(2),
    teamID CHAR(3) PRIMARY KEY,
    franchID CHAR(3),
    divID INTEGER,
    Ranking INTEGER,
    G INTEGER,
    Ghome INTEGER,
    W INTEGER,
    L INTEGER,
    DivWin INTEGER,
    WCWin INTEGER,
    LgWin CHAR(1),
    WSWin INTEGER,
    R INTEGER,
    AB INTEGER,
    H INTEGER,
    2B INTEGER,
    3B INTEGER,
    HR INTEGER,
    BB INTEGER,
    SO INTEGER,
    SB INTEGER,
    CS INTEGER,
    HBP INTEGER,
    SF INTEGER,
    RA INTEGER,
    ER INTEGER,
    ERA FLOAT(3),
    CG INTEGER,
    SHO INTEGER,
    SV INTEGER,
    IPouts INTEGER,
    HA INTEGER,
    HRA INTEGER,
    BBA INTEGER,
    SOA INTEGER,
    E INTEGER,
    DP INTEGER,
    FP FLOAT(3),
    Name VARCHAR(200),
    park VARCHAR(200),
    attendance INTEGER,
    BPF INTEGER,
    PPF INTEGER,
    teamIDBR CHAR(3),
    teamIDlahman45 CHAR(3),
    teamIDretro CHAR(3)
);

    
CREATE TABLE `Pitching`(
        playerID VARCHAR(200) PRIMARY KEY,
        yearID INTEGER,
        stint INTEGER,
        teamID CHAR(3) NOT NULL,
        lgID CHAR(3),
        W INTEGER,
        L INTEGER,
        G INTEGER,
        GS INTEGER,
        CG INTEGER,
        SHO INTEGER,
        SV INTEGER,
        IPouts INTEGER,
        H INTEGER,
        ER INTEGER,
        HR INTEGER,
        BB INTEGER,
        SO INTEGER,
        BAOpp FLOAT(3),
        ERA INTEGER,
        IBB INTEGER,
        WP INTEGER,
        HBP INTEGER,
        BK INTEGER,
        BFP INTEGER,
        GF INTEGER,
        R INTEGER,
        SH INTEGER,
        SF INTEGER,
        GIDP INTEGER,
        FOREIGN KEY (teamID) REFERENCES Teams(teamID)
);

CREATE TABLE `Batting`(
   playerID VARCHAR(200),
   yearID INTEGER,
   stint INTEGER,
   teamID CHAR(3) NOT NULL,
   lgID CHAR(2),
   W INTEGER,
   L INTEGER,
   G INTEGER,
   GS INTEGER,
   CG INTEGER,
   SHO INTEGER,
   SV INTEGER,
   IPouts INTEGER,
   H INTEGER,
   ER INTEGER,
   HR INTEGER,
   BB INTEGER,
   SO INTEGER,
   BAOpp INTEGER,
   ERA INTEGER,
   IBB INTEGER,
   WP INTEGER,
   HBP INTEGER,
   BK INTEGER,
   BFP INTEGER,
   GF INTEGER,
   R INTEGER,
   SH INTEGER,
   SF INTEGER,
   GIDP INTEGER,
   FOREIGN KEY (teamID) REFERENCES Teams(teamID)
);

   