CREATE TABLE `Teams`(
    yearID INTEGER NOT NULL,
    lgID CHAR(2),
    teamID CHAR(3) NOT NULL,
    franchID CHAR(3),
    divID INTEGER,
    Ranking INTEGER,
    G INTEGER,
    Ghome INTEGER,
    W INTEGER,
    L INTEGER,
    DivWin INTEGER,
    WCWin INTEGER,
    LgWin CHAR(1),
    WSWin INTEGER,
    R INTEGER,
    AB INTEGER,
    H INTEGER,
    2B INTEGER,
    3B INTEGER,
    HR INTEGER,
    BB INTEGER,
    SO INTEGER,
    SB INTEGER,
    CS INTEGER,
    HBP INTEGER,
    SF INTEGER,
    RA INTEGER,
    ER INTEGER,
    ERA FLOAT(3),
    CG INTEGER,
    SHO INTEGER,
    SV INTEGER,
    IPouts INTEGER,
    HA INTEGER,
    HRA INTEGER,
    BBA INTEGER,
    SOA INTEGER,
    E INTEGER,
    DP INTEGER,
    FP FLOAT(3),
    Name VARCHAR(200),
    park VARCHAR(200),
    attendance INTEGER,
    BPF INTEGER,
    PPF INTEGER,
    teamIDBR CHAR(3),
    teamIDlahman45 CHAR(3),
    teamIDretro CHAR(3),
    PRIMARY KEY (teamID, yearID)
);

    
CREATE TABLE `Pitching`(
        playerID VARCHAR(200) NOT NULL,
        yearID INTEGER NOT NULL,
        stint INTEGER,
        teamID CHAR(3) NOT NULL,
        lgID CHAR(3),
        W INTEGER,
        L INTEGER,
        G INTEGER,
        GS INTEGER,
        CG INTEGER,
        SHO INTEGER,
        SV INTEGER,
        IPouts INTEGER,
        H INTEGER,
        ER INTEGER,
        HR INTEGER,
        BB INTEGER,
        SO INTEGER,
        BAOpp FLOAT(3),
        ERA INTEGER,
        IBB INTEGER,
        WP INTEGER,
        HBP INTEGER,
        BK INTEGER,
        BFP INTEGER,
        GF INTEGER,
        R INTEGER,
        PRIMARY KEY(playerID, yearID, teamID),
        FOREIGN KEY (teamID, yearID) REFERENCES Teams(teamID, yearID)
);

CREATE TABLE `Batting`(
   playerID VARCHAR(200) NOT NULL,
   yearID INTEGER NOT NULL,
   stint INTEGER,
   teamID CHAR(3) NOT NULL,
   lgID CHAR(2) NOT NULL,
   G INTEGER,
   AB INTEGER,
   R INTEGER,
   H INTEGER,
   2B INTEGER,
   3B INTEGER,
   HR INTEGER,
   RBI INTEGER,
   SB INTEGER,
   CS INTEGER,
   BB INTEGER,
   SO INTEGER,
   IBB INTEGER,
   HBP INTEGER,
   SH INTEGER,
   SF INTEGER,
   GIDP INTEGER,
   PRIMARY KEY(playerID, yearID, teamID),
   FOREIGN KEY (teamID, yearID) REFERENCES Teams(teamID, yearID)
);

   